In [1]:
A=[1 2;3 4;5 6]
B=[11 12;13 14;15 16]
C=[1 1;2 2]

A =

   1   2
   3   4
   5   6

B =

   11   12
   13   14
   15   16

C =

   1   1
   2   2



In [2]:
A*C

ans =

    5    5
   11   11
   17   17



In [3]:
A.*C %.*는 요소별 곱셈이다.

error: product: nonconformant arguments (op1 is 3x2, op2 is 2x2)


In [4]:
A.*B %행렬 사이즈가 같아야하고 각 대응하는 요소끼리를 곱한다

ans =

   11   24
   39   56
   75   96



In [6]:
A.^2 %각 요소는 제곱이 된다

ans =

    1    4
    9   16
   25   36



In [7]:
v=[1;2;3]

v =

   1
   2
   3



In [8]:
1./v

ans =

   1.0000
   0.5000
   0.3333



In [9]:
log(v)

ans =

        0
   0.6931
   1.0986



In [10]:
exp(v)

ans =

    2.7183
    7.3891
   20.0855



In [11]:
abs(v) %절댓값

ans =

   1
   2
   3



In [12]:
abs([-1;2;-5])

ans =

   1
   2
   5



In [13]:
-v

ans =

  -1
  -2
  -3



In [14]:
ones(2,3) % 1로된 행렬만든다

ans =

   1   1   1
   1   1   1



In [15]:
C=2*ones(2,3)

C =

   2   2   2
   2   2   2



In [16]:
w=zeros(1,3)

w =

  0  0  0



In [17]:
w=rand(1,3) %random

w =

   0.698538   0.087727   0.666921



In [18]:
v+ones(length(v),1)

ans =

   2
   3
   4



In [19]:
v+1 %위에랑 똑같은 결과

ans =

   2
   3
   4



In [20]:
A

A =

   1   2
   3   4
   5   6



In [22]:
A' % 전치행렬구해줌 (Transpose)

ans =

   1   3   5
   2   4   6



In [23]:
a=[1 15 2 0.5]

a =

    1.0000   15.0000    2.0000    0.5000



In [25]:
val=max(a) % 최댓값 구해줌

val = 15


In [26]:
[val,index]=max(a)

val = 15
index = 2


In [27]:
a<3 % 맞으면 1 틀리면 0

ans =

  1  0  1  1



In [29]:
find(a<3) # 해당되는 부분 인덱스를 구해줌

ans =

   1   3   4



In [31]:
A=magic(3) # 마방진 만들어줌. 기계학습에서 쓸모는 없으나 응아저씨는 3*3행렬 만들때 쓴다함

A =

   8   1   6
   3   5   7
   4   9   2



In [32]:
[row,column]=find(A>=7) %(1,1) (3,2) (2,3)해당된다

row =

   1
   3
   2

column =

   1
   2
   3



In [33]:
sum(A) % +

ans =

   15   15   15



In [41]:
sum(sum(A))

ans = 45


In [34]:
prod(A) % *

ans =

   96   45   84



In [36]:
floor(a) % 끝자리 버림

ans =

    1   15    2    0



In [37]:
ceil(a)  % 반올림

ans =

    1   15    2    1



In [39]:
max(A,[],1) # 1이 의미하는 건 열의 원소중 최댓값

ans =

   8   9   7



In [40]:
max(A,[],2) # 2이 의미하는 건 행의 원소중 최댓값

ans =

   8
   7
   9



In [42]:
A=magic(9)

A =

   47   58   69   80    1   12   23   34   45
   57   68   79    9   11   22   33   44   46
   67   78    8   10   21   32   43   54   56
   77    7   18   20   31   42   53   55   66
    6   17   19   30   41   52   63   65   76
   16   27   29   40   51   62   64   75    5
   26   28   39   50   61   72   74    4   15
   36   38   49   60   71   73    3   14   25
   37   48   59   70   81    2   13   24   35



In [43]:
sum(A,1)

ans =

   369   369   369   369   369   369   369   369   369



In [44]:
sum(A,2)

ans =

   369
   369
   369
   369
   369
   369
   369
   369
   369



In [45]:
eye(9)

ans =

Diagonal Matrix

   1   0   0   0   0   0   0   0   0
   0   1   0   0   0   0   0   0   0
   0   0   1   0   0   0   0   0   0
   0   0   0   1   0   0   0   0   0
   0   0   0   0   1   0   0   0   0
   0   0   0   0   0   1   0   0   0
   0   0   0   0   0   0   1   0   0
   0   0   0   0   0   0   0   1   0
   0   0   0   0   0   0   0   0   1



In [46]:
A.*eye(9)

ans =

   47    0    0    0    0    0    0    0    0
    0   68    0    0    0    0    0    0    0
    0    0    8    0    0    0    0    0    0
    0    0    0   20    0    0    0    0    0
    0    0    0    0   41    0    0    0    0
    0    0    0    0    0   62    0    0    0
    0    0    0    0    0    0   74    0    0
    0    0    0    0    0    0    0   14    0
    0    0    0    0    0    0    0    0   35



In [47]:
sum(sum(A.*eye(9)))

ans = 369


In [50]:
flipud(eye(9)) % 행렬 뒤집어줌

ans =

Permutation Matrix

   0   0   0   0   0   0   0   0   1
   0   0   0   0   0   0   0   1   0
   0   0   0   0   0   0   1   0   0
   0   0   0   0   0   1   0   0   0
   0   0   0   0   1   0   0   0   0
   0   0   0   1   0   0   0   0   0
   0   0   1   0   0   0   0   0   0
   0   1   0   0   0   0   0   0   0
   1   0   0   0   0   0   0   0   0



In [51]:
A=magic(3)

A =

   8   1   6
   3   5   7
   4   9   2



In [53]:
pinv(A) % 역행렬 구함

ans =

   0.147222  -0.144444   0.063889
  -0.061111   0.022222   0.105556
  -0.019444   0.188889  -0.102778

